### ISSUE TITLE
once music file downloaded, can't getSavedUrl next time 

### ISSUE THREAD

**Issue by zinwalin** [tanhakabir/SwiftAudioPlayer#58]
One file has been downloaded, then terminated app, and start app to call getSavedUrl, it return nil. but actually the file exist in app container. 

![image](https://user-images.githubusercontent.com/5416196/100966663-6a3a2b00-3568-11eb-8316-c8ec52ab862c.png)

**Comment by fayinsky** [comment]
There's a bug in FileStorage's **locate** function. It is supposed to scan all files saved in _Documents_ folder and see if a file containing correct hash key generated from remote URL exists or not. However, the code only managed to retrieve the local URL for _Documents_ folder itself rather than the files within.

My fix for the **locate** function is as follows:
```
static func locate(_ id: ID) -> URL? {
    let folderURLs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
    if folderURLs.count == 0 {
        return nil
    }
    if let urls = try? FileManager.default.contentsOfDirectory(at: folderURLs[0], includingPropertiesForKeys: nil) {
        for url in urls {
            if url.absoluteString.contains(id) && url.pathExtension != "" {
                _ = getUrl(givenId: id, andFileExtension: url.pathExtension)
                return url
            }
        }
    }
    return nil
}
```
